! @Execute
SUBROUTINE KINWAVE(RUNOFF_NUM_STEPS,RUNOFF_CUM_TIME,
     1   RUNOFF_CUM_AMT,INFLOW,PLANE_ROUGH,PLANE_SLOPE,
     1   PLANE_LENGTH,HYD_EXIT,RUNOFF_HYDRO,QOUT,EFFDRN)
 
C     PROGRAM KINWAVE
C
C     NUMERICAL SOLUTION OF THE KINEMATIC WAVE EQUATION -
C     EXPLICIT FINITE DIFFERENCE SOLUTION FOR OVERLAND FLOW
C
    USE, INTRINSIC :: ISO_C_BINDING
    IMPLICIT NONE
    
    ! @In
    INTEGER(C_INT) :: RUNOFF_NUM_STEPS
    
    ! @In
    REAL(C_DOUBLE), DIMENSION(RUNOFF_NUM_STEPS) :: RUNOFF_CUM_TIME
    
    ! @In
    REAL(C_DOUBLE), DIMENSION(RUNOFF_NUM_STEPS) :: RUNOFF_CUM_AMT
    
    ! @In
    REAL(C_DOUBLE), DIMENSION(RUNOFF_NUM_STEPS) :: INFLOW
    
    ! @In
    REAL(C_DOUBLE) :: PLANE_ROUGH
    
    ! @In
    REAL(C_DOUBLE) :: PLANE_SLOPE
    
    ! @In
    REAL(C_DOUBLE) :: PLANE_LENGTH
    
    ! @In
    REAL(C_DOUBLE) :: HYD_EXIT
    
    ! @In
    REAL(C_DOUBLE), DIMENSION(RUNOFF_NUM_STEPS) :: RUNOFF_HYDRO
    
    ! @Out
    REAL(C_DOUBLE) :: QOUT
    
    ! @Out
    REAL(C_DOUBLE) :: EFFDRN
    
C
C     MODULE INPUTS
C
C     RUNOFF_NUM_STEPS   NUMBER OF TIME AND RUNOFF POINTS DETERMINED 
C                        BY GREEN-AMPT INFILTRATION
C     RUNOFF_CUM_TIME    TIME STEP FOR EACH RUNOFF POINT (HR)
C     RUNOFF_CUM_AMT     AMOUNT OF RUNOFF DETERMINED BY GREEN-AMPT 
C                        INFILTRATION (CM)
C     INFLOW             INFLOW (RUNON) FROM UPPER PLANE (CM)
C     PLANE_ROUGH        PLANE MANNING ROUGHNESS
C     PLANE_SLOPE        PLANE SLOPE (M/M)
C     PLANE_LENGTH       PLANE LENGTH (M)
C     HYD_EXIT           MINIMUM FLOW THRESHOLD FOR EXITING RUNOFF
C                        HYDROGRAPH COMPUTATIONS (M**2/S)
C
C     MODULE OUTPUTS
C
C     RUNOFF_HYDRO       RUNOFF HYDROGRAPH (M**2/S)
C     QOUT               PEAK FLOW RATE (M**2/S)
C     EFFDRN             EFFECTIVE DURATION (S)  

C
C     PARAMETER DEFINITIONS
C
      INTEGER MXTSTP
      PARAMETER (MXTSTP = 5000)
C
C     PASSED IN ARGUMENTS
C
!      REAL*8 RUNOFF_CUM_TIME(MXTSTP),RUNOFF_CUM_AMT(MXTSTP),
!     1    INFLOW(MXTSTP),RUNOFF_HYDRO(MXTSTP)
!      REAL*8 PLANE_ROUGH,PLANE_SLOPE,PLANE_LENGTH,HYD_EXIT,QOUT,EFFDRN
!      
!      INTEGER RUNOFF_NUM_STEPS
C
C     LOCAL VARIABLES
C
      REAL*8 AAVG,ALPHA,DT,DTDX,DX,DXDT,ENDT,KINEMATIC_M,TIME,THETA,
     1   RUNOFF_TOT_TIME
      REAL*8 DIFF_RUNOFF_TIME(MXTSTP),DIFF_RUNOFF_AMT(MXTSTP),
     1   RO_DEPTH(MXTSTP),RO_RATE(MXTSTP),AJ(MXTSTP),AJP1(MXTSTP),
     1   QJP1(MXTSTP),RUNOFF_INC_TIME(MXTSTP)
      INTEGER I,J,NODES,INC_RO_STEPS,MX_HYD_STEPS,MX_RO_STEPS
C
C     INITIALIZE LOCAL ARRAYS
C
      DATA DIFF_RUNOFF_TIME,DIFF_RUNOFF_AMT,RO_DEPTH,RO_RATE,AJ,AJP1,
     1   QJP1,RUNOFF_INC_TIME /MXTSTP*0.0,MXTSTP*0.0,MXTSTP*0.0,
     1   MXTSTP*0.0,MXTSTP*0.0,MXTSTP*0.0,MXTSTP*0.0,MXTSTP*0.0/
C
      DATA KINEMATIC_M,NODES /1.667D0,10/
      DATA DT/0.008333D0/    ! DT IN HRS (CORRRESPONDS TO 0.5 MINS)
C
C     TEST DATA SET FOR 2 IN/HR STORM WITH 30 MIN DURATION
C     AND 5 MIN TIME-INTENSITY INTERVALS
C
C     DATA RUNOFF_NUM_STEPS /7/
C     DATA RUNOFF_CUM_TIME /0.0,0.083333,0.1666666,0.25,0.333333,
C    1   0.416667,0.50,4993*0.0/   ! RUNOFF_CUM_TIME IN HRS
C     DATA RUNOFF_CUM_AMT /0.0,0.423333,0.846667,1.27,1.69333,
C    1   2.11666,2.54,4993*0.0/    ! RUNOFF_CUM_AMT IN CM
C     DATA PLANE_ROUGH,PLANE_SLOPE,PLANE_LENGTH /0.025,0.0016,182.882/
C     DATA HYD_EXIT /1.0E-04/ 
C
C     TEST DATA SET WITH 23 RUNOFF AMOUNT - RUNOFF TIME PAIRS
C
C     DATA RUNOFF_NUM_STEPS /23/
C     DATA RUNOFF_CUM_TIME /1.113,1.147,1.184,1.225,1.268,1.313,1.362,
C    1   1.413,1.467,1.523,1.582,1.644,1.707,1.773,1.842,1.913,1.986,
C    1   2.061,2.138,2.217,2.299,2.382,2.417,4977*0.0/   ! RUNOFF_CUM_TIME IN HRS
C     DATA RUNOFF_CUM_AMT /0.014,0.040,0.078,0.128,0.189,0.262,0.347,
C    1   0.442,0.548,0.665,0.665,0.665,0.665,0.665,0.665,0.665,1.760,
C    1   1.954,2.157,2.369,2.589,2.817,2.912,4977*0.0/    ! RUNOFF_CUM_AMT IN CM
C     DATA RUNOFF_CUM_AMT /0.014,0.040,0.078,0.128,0.189,0.262,0.347,
C    1   0.442,0.548,0.665,0.792,0.929,1.076,1.223,1.400,1.575,1.760,
C    1   1.954,2.157,2.369,2.589,2.817,2.912,4977*0.0/    ! RUNOFF_CUM_AMT IN CM
C     DATA PLANE_ROUGH,PLANE_SLOPE,PLANE_LENGTH /0.025,0.0016,182.882/
C     DATA HYD_EXIT /1.0E-04/ 
C
C     OPEN (3,FILE='KWAVE.OUT',STATUS='UNKNOWN')
C
      WRITE(*,*) "AT TOP OF KINWAVE"
C
C     SET GRID NODE SPACING
C 
      DX = PLANE_LENGTH/FLOAT(NODES-1)
C
C     CONVERT DTDX,DXDT TO SEC/M AND M/SEC
C      
      DTDX = DT*3600.0D0/DX
      DXDT = DX/(DT*3600.0D0)
C
C     CALCULATE TOTAL DURATION OF THE RUNOFF HYDROGRAPH (HRS)
C
      RUNOFF_TOT_TIME = RUNOFF_CUM_TIME(RUNOFF_NUM_STEPS)-
     1   RUNOFF_CUM_TIME(1)
C
      ENDT = RUNOFF_TOT_TIME*4.0D0
C
C     MAXIMUM TIME STEPS FOR HYDROGRAPH AND RUNOFF DURATION
C
      MX_HYD_STEPS = NINT(ENDT/DT) + 1
      MX_RO_STEPS = NINT(RUNOFF_TOT_TIME/DT)+1
C
C     CALCULATE INCREMENTAL RAINFALL-RUNOFF ARRAYS 
C
      DO I = 1, RUNOFF_NUM_STEPS-1
         IF (I.EQ.1) THEN 
            RUNOFF_INC_TIME(I) = RUNOFF_CUM_TIME(I+1) - 
     1      RUNOFF_CUM_TIME(I) 
         ELSE
            RUNOFF_INC_TIME(I) = RUNOFF_INC_TIME(I-1) +
     1         (RUNOFF_CUM_TIME(I+1) - RUNOFF_CUM_TIME(I)) 
         ENDIF
C
         DIFF_RUNOFF_TIME(I) = RUNOFF_CUM_TIME(I+1) - 
     1      RUNOFF_CUM_TIME(I)
C
         DIFF_RUNOFF_AMT(I) = RUNOFF_CUM_AMT(I+1) -
     1      RUNOFF_CUM_AMT(I)         
      END DO
C
C     INITIALIZE TIME AND TIME STEP INCREMENTER
C
      TIME = 0.0
      INC_RO_STEPS = 1
C
C     CALCULATE RUNOFF DEPTH AND RATE ARRAYS FOR USE IN 
C     EXPLICIT KINEMATIC WAVE NUMERICAL SOLUTION
C
      DO I = 1,MX_HYD_STEPS
C
         TIME = TIME + DT
C
         WRITE(*,*)" I= ",I," TIME= ",TIME," DT= ",DT
C
         IF(I.LE.MX_RO_STEPS) THEN
            RO_DEPTH(I) = (DIFF_RUNOFF_AMT(INC_RO_STEPS)/
     1         (DIFF_RUNOFF_TIME(INC_RO_STEPS)/DT))*0.01D0        ! CM TO M
            RO_RATE(I) = (DIFF_RUNOFF_AMT(INC_RO_STEPS)/
     1         (DIFF_RUNOFF_TIME(INC_RO_STEPS)*3600.0D0))*0.01D0  ! CM/S TO M/S 
         ELSE
            RO_DEPTH(I) = 0.0D0
            RO_RATE(I) = 0.0D0
         ENDIF
C
         IF(TIME.GT.RUNOFF_INC_TIME(INC_RO_STEPS)) INC_RO_STEPS = 
     1      INC_RO_STEPS+1
C
         WRITE(*,*)"RO_DEPTH(I)= ",RO_DEPTH(I),"RO_RATE(I)=",RO_RATE(I)
C  
      END DO
C         
C     SET INITIAL AND UPSTREAM BOUNDARY CONDITIONS
C
      DO I = 1,NODES + 1
         AJP1(I) = 0.0
         AJ(I) = 0.0
         QJP1(I) = 0.0
C        QJP1(I) = INFLOW(I)   !  SET IF INFLOW FROM UPPER PLANE
      END DO
C
C     CALCULATE PARAMETER ALPHA
C
      ALPHA = (1.49/PLANE_ROUGH)*SQRT(PLANE_SLOPE)
C
C     RE-INITIALIZE TIME AND INITIALIZE QOUT
C
      TIME = 0.0D0
      QOUT = 0.0D0
C
C     TIME LOOP
C
      DO J = 1,MX_HYD_STEPS
C
C        J,J+1 REPRESENT T,T+DT TIME STEPS
C
         TIME = TIME + DT
C
C        DISTANCE LOOP
C
         DO I = 1,NODES
C
C           I,I+1 REPRESENT X,X+DX GRID POINTS
C
            AAVG = (AJ(I+1)+AJP1(I))/2.0D0
C
            THETA = ALPHA*KINEMATIC_M*(AAVG)**(KINEMATIC_M-1.0)*DTDX
C
C           COURANT CONDITION CHECK FOR WAVE CELERITY -
C           SWITCH TO DIFFERENT SOLUTION IF THETA >= 1.0
C
            IF (THETA.GE.1.0D0) THEN
               QJP1(I+1) = QJP1(I) + (RO_RATE(J)*DX) - 
     1         DXDT*(AJP1(I)-AJ(I))
               AJP1(I+1) = (QJP1(I+1)/ALPHA)**(1/KINEMATIC_M)
               WRITE (*,*) "WARNING: THETA > 1"
            ELSE
               AJP1(I+1) = RO_DEPTH(J) + AJ(I+1) 
     1                     -ALPHA*DTDX*AJ(I+1)*AAVG**(KINEMATIC_M-1.0D0)
     1                     +ALPHA*DTDX*AJ(I)**KINEMATIC_M
               QJP1(I+1) = ALPHA*AJP1(I+1)**KINEMATIC_M
            END IF
C
         END DO   ! END OF SPACE (GRID NODES) LOOP
C
C        SET RUNOFF HYDROGRAPH FOR TIME STEPS AND FINAL NODE ON PLANE
C
         RUNOFF_HYDRO(J) = QJP1(NODES)
C
C        SET PEAK RUNOFF QOUT (M**2/S)
C
         IF(RUNOFF_HYDRO(J).GT.QOUT) QOUT = RUNOFF_HYDRO(J)
C
         WRITE(*,*) "J= ",J,"  RUNOFF_HYDRO=",RUNOFF_HYDRO(J)
C
C        SET ALTERNATIVE EXIT CONDITION FOR FLOW CALCULATION 
C
         IF(TIME.GT.RUNOFF_TOT_TIME.AND.RUNOFF_HYDRO(J).LT.HYD_EXIT) 
     1      EXIT   ! EXIT IF FLOW LESS THAN INPUT THRESHOLD CONDITION
C
C        WRITE (3,1000) TIME,QJP1(NODES)*PLANE_LENGTH,
C    1      TIME*60.0,QJP1(NODES)*PLANE_LENGTH*(3.281**3)
C
         DO I = 2,NODES
            AJ(I) = AJP1(I)
         END DO
C
      END DO  ! END OF TIME LOOP
C
C     CALCULATE EFFECTIVE DURATION (S)
C
      EFFDRN = (RUNOFF_CUM_AMT(RUNOFF_NUM_STEPS)/100.0D0)/
     1      (QOUT/PLANE_LENGTH)
C
      WRITE(*,*) "RUNOFF_CUM_AMT = ",RUNOFF_CUM_AMT(RUNOFF_NUM_STEPS)
      WRITE(*,*) "QOUT = ",QOUT," PLANE_LENGTH = ",PLANE_LENGTH       
C
      WRITE (*,*) QOUT*PLANE_LENGTH,EFFDRN
C
C     CLOSE (3)
C
C1000 FORMAT (1X,F9.4,2X,F10.6,10X,F9.4,2X,F10.6)
C
      RETURN
C
      END SUBROUTINE KINWAVE
C
C     END PROGRAM KINWAVE